# Generated by Django 4.0.2 on 2024-05-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_remove_form_see_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='cover_photo',
            field=models.ImageField(default='', upload_to='ImageStore'),
        ),
    ]
