# Generated by Django 4.0.2 on 2024-05-15 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_form_cover_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.form')),
            ],
        ),
    ]
