# Generated by Django 4.0.2 on 2024-05-16 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_phonenumbers_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageSent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=10000)),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index.form')),
            ],
        ),
    ]
