# Generated by Django 4.0.2 on 2024-06-11 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_messagesent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_location_name', models.CharField(blank=True, max_length=100, null=True)),
                ('event_latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('event_longtude', models.CharField(blank=True, max_length=50, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_form', to='index.form')),
            ],
        ),
    ]
