# Generated by Django 4.0.2 on 2024-06-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_eventlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='collect_email',
            field=models.BooleanField(default=True),
        ),
    ]
